In [6]:
""" Импортируйте библиотеки pandas и numpy.
    Загрузите "Boston House Prices dataset" из встроенных наборов данных библиотеки sklearn. Создайте датафреймы X и y из 
    этих данных.
    Разбейте эти датафреймы на тренировочные (X_train, y_train) и тестовые (X_test, y_test) с помощью функции 
    train_test_split так, чтобы размер тестовой выборки составлял 30% от всех данных, при этом аргумент random_state должен 
    быть равен 42.
    Создайте модель линейной регрессии под названием lr с помощью класса LinearRegression из модуля sklearn.linear_model.
    Обучите модель на тренировочных данных (используйте все признаки) и сделайте предсказание на тестовых.
    Вычислите R2 полученных предказаний с помощью r2_score из модуля sklearn.metrics.
"""
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

boston = load_boston()
data = boston.data
target = boston.target
feature_names = boston.feature_names
X = pd.DataFrame(data, columns=feature_names)
y = pd.DataFrame(target, columns = ['price'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
R2 = r2_score(y_test, y_pred)
R2

0.7112260057484887

In [8]:
""" Создайте модель под названием model с помощью RandomForestRegressor из модуля sklearn.ensemble.
    Сделайте агрумент n_estimators равным 1000, max_depth должен быть равен 12 и random_state сделайте равным 42.
    Обучите модель на тренировочных данных аналогично тому, как вы обучали модель LinearRegression, но при этом в метод 
    fit вместо датафрейма y_train поставьте y_train.values[:, 0], чтобы получить из датафрейма одномерный массив Numpy,
    так как для класса RandomForestRegressor в данном методе для аргумента y предпочтительно применение массивов вместо 
    датафрейма.
    Сделайте предсказание на тестовых данных и посчитайте R2. Сравните с результатом из предыдущего задания.
    Напишите в комментариях к коду, какая модель в данном случае работает лучше.
"""
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=1000, max_depth=12, random_state=42)
model.fit(X_train, y_train.values[:, 0])
y_pred_2 = model.predict(X_test)
R2_ = r2_score(y_test, y_pred_2)
R2_

# В данном случае модель, созданная с помощью RandomForestRegressor, работает лучше, чем модель, созданная с помощью LinearRegression


0.87472606157312

In [18]:
""" Вызовите документацию для класса RandomForestRegressor, найдите информацию об атрибуте feature_importances_.
    С помощью этого атрибута найдите сумму всех показателей важности, установите, какие два признака показывают 
    наибольшую важность.
"""
importances = model.feature_importances_
importances_sum = sum(importances)
importances_dict = {a:b for a, b in zip(feature_names, importances)}
print(f"Показатели важности: {importances_dict}\nСумма всех показателей важности: {importances_sum}\nПризнаки с наибольшей важностью:", sorted(importances_dict, key=importances_dict.get, reverse=True)[:2])

Показатели важности: {'CRIM': 0.03167574073875602, 'ZN': 0.0015425166262328857, 'INDUS': 0.007138131415845557, 'CHAS': 0.0012362448947738866, 'NOX': 0.0142689698753483, 'RM': 0.4026817857034993, 'AGE': 0.014298644996729816, 'DIS': 0.06397256527230023, 'RAD': 0.00528121831288784, 'TAX': 0.011524934553144586, 'PTRATIO': 0.018081076405025417, 'B': 0.012450853014007697, 'LSTAT': 0.4158473181914483}
Сумма всех показателей важности: 1.0
Признаки с наибольшей важностью: ['LSTAT', 'RM']


In [36]:
""" Импортируйте из соответствующих модулей RandomForestClassifier, GridSearchCV и train_test_split.
    Загрузите датасет creditcard.csv и создайте датафрейм df.
    С помощью метода value_counts с аргументом normalize=True убедитесь в том, что выборка несбалансирована. 
    Используя метод info, проверьте, все ли столбцы содержат числовые данные и нет ли в них пропусков. Примените следующую 
    настройку, чтобы можно было просматривать все столбцы датафрейма:
    pd.options.display.max_columns = 100.
    Просмотрите первые 10 строк датафрейма df.
    Создайте датафрейм X из датафрейма df, исключив столбец Class. Создайте объект Series под названием y из столбца Class.
    Разбейте X и y на тренировочный и тестовый наборы данных при помощи функции train_test_split, используя аргументы: 
    test_size=0.3, random_state=100, stratify=y.
    У вас должны получиться объекты X_train, X_test, y_train и y_test. Просмотрите информацию о их форме.
    Для поиска по сетке параметров задайте такие параметры:
    parameters = [{'n_estimators': [10, 15],
    'max_features': np.arange(3, 5),
    'max_depth': np.arange(4, 7)}]
    Создайте модель GridSearchCV со следующими аргументами:
    estimator=RandomForestClassifier(random_state=100),
    param_grid=parameters,
    scoring='roc_auc',
    cv=3.
    Обучите модель на тренировочном наборе данных (может занять несколько минут).
    Просмотрите параметры лучшей модели с помощью атрибута best_params_.
    Предскажите вероятности классов с помощью полученнной модели и метода predict_proba.
    Из полученного результата (массив Numpy) выберите столбец с индексом 1 (вероятность класса 1) и запишите в массив 
    y_pred_proba. Из модуля sklearn.metrics импортируйте метрику roc_auc_score.
    Вычислите AUC на тестовых данных и сравните с результатом,полученным на тренировочных данных, используя в качестве 
    аргументов массивы y_test и y_pred_proba.
"""
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score

df = pd.read_csv("creditcard.csv")
print(df.value_counts(["Class"],normalize=True))
print(df.info())
pd.options.display.max_columns = 100
print(df.head(10))
X = df.drop("Class", axis=1)
y = df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100, stratify=y)
print(f"X_train.shape:{X_train.shape}, X_test.shape:{X_test.shape}, y_train.shape:{y_train.shape}, y_test.shape:{y_test.shape}")
parameters = [{'n_estimators': [10, 15], 'max_features': np.arange(3, 5), 'max_depth': np.arange(4, 7)}]
clf = GridSearchCV(estimator=RandomForestClassifier(random_state=100), param_grid=parameters, scoring='roc_auc', cv=3)
clf.fit(X_train, y_train)
print("Параметры лучшей модели:", clf.best_params_)
y_pred_proba = clf.predict_proba(X_test)
y_pred_train = clf.predict_proba(X_train)
y_pred_proba = y_pred_proba[:, 1]
y_pred_train = y_pred_train[:, 1]
auc_test = roc_auc_score(y_test, y_pred_proba)
auc_test_train = roc_auc_score(y_train, y_pred_train)
print(f"Значение AUC для тестовых данных:\n{auc_test}\nДля тренировочных данных:\n{auc_test_train}")

Class
0        0.998273
1        0.001727
dtype: float64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  floa

In [92]:
""" 1). Загрузите датасет Wine из встроенных датасетов sklearn.datasets с помощью функции load_wine в переменную data.
    2). Полученный датасет не является датафреймом. Это структура данных, имеющая ключи аналогично словарю. Просмотрите 
    тип данных этой структуры данных и создайте список data_keys, содержащий ее ключи.
    3). Просмотрите данные, описание и названия признаков в датасете. Описание нужно вывести в виде привычного, аккуратно 
    оформленного текста, без обозначений переноса строки, но с самими переносами и т.д.4). Сколько классов содержит целевая 
    переменная датасета? Выведите названия классов.
    5). На основе данных датасета (они содержатся в двумерном массиве Numpy) и названий признаков создайте датафрейм под 
    названием X.
    6). Выясните размер датафрейма X и установите, имеются ли в нем пропущенные значения.
    7). Добавьте в датафрейм поле с классами вин в виде чисел, имеющих тип данных numpy.int64. Название поля - 'target'.
    8). Постройте матрицу корреляций для всех полей X. Дайте полученному датафрейму название X_corr.
    9). Создайте список high_corr из признаков, корреляция которых с полем target по абсолютному значению превышает 0.5 
    (причем, само поле target не должно входить в этот список).
    10). Удалите из датафрейма X поле с целевой переменной. Для всех признаков, названия которых содержатся в списке 
    high_corr, вычислите квадрат их значений и добавьте в датафрейм X соответствующие поля с суффиксом '_2', добавленного 
    к первоначальному названию признака. Итоговый датафрейм должен содержать все поля, которые, были в нем изначально, а 
    также поля с признаками из списка high_corr, возведенными в квадрат. Выведите описание полей датафрейма X с помощью 
    метода describe.
"""
from sklearn.datasets import load_wine

data = load_wine()
print(type(data))
data_keys = data.keys()
pd.options.display.max_columns = 100
print(data_keys)
print(data.data)
print(data.DESCR)
print(data.feature_names)
print(f"Переменная содержит {len(np.unique(data.target))} класса - {np.unique(data.target)}\n")
X = pd.DataFrame(data.data, columns=data.feature_names)
print(X.info())
X['target'] = data.target.astype(np.int64)
X_corr = X.corr()
print("Матрица корреляций для всех полей:\n", X_corr)
high_corr = X_corr.loc[(abs(X_corr['target']) > 0.5) & (abs(X_corr['target']) != 1.0)]
high_corr = high_corr['target'].index
print("Признаки, корреляция которых с полем target по абсолютному значению превышает 0.5:\n", high_corr)
X = X.drop('target', axis=1)
for el in high_corr:
    X[el + "_2"] = X[el] ** 2
X.describe()
    

<class 'sklearn.utils.Bunch'>
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wi

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  alcalinity_of_ash_2  \
0                            3.92   1065.0               243.36   
1                            3.40   1050.0               125.44   
2                            3.17   1185.0               345.96   
3                            3.45   1480.0               282.24   
4                            2.93    735.0               441.00   
..                            ...      ...                  ...   
173                          1.74    740.0               420.25   
174                          1.56    750.0               529.00   
175                          1.56    835.0               400.00   
176                          1.62    840.0               400.00   
177                          1.60    560.0               600.25   

     total_phenols_2  flavanoids_2   hue_2  od280/od315_of_diluted_wines_2  \
0             7.8400        9.3636  1.0816                         15.3664   
1             7.0225        7.6176  1.1025                         11.5600   
2             7.8400       10.4976  1.0609                         10.0489   
3            14.8225       12.1801  0.7396                         11.9025   
4             7.8400        7.2361  1.0816                          8.5849   
..               ...           ...     ...                             ...   
173           2.8224        0.3721  0.4096                          3.0276   
174           3.2400        0.5625  0.4900                          2.4336   
175           2.5281        0.4761  0.3481                          2.4336   
176           2.7225        0.4624  0.3600                          2.6244   
177           4.2025        0.5776  0.3721                          2.5600   

     proline_2  
0    1134225.0  
1    1102500.0  
2    1404225.0  
3    2190400.0  
4     540225.0  
..         ...  
173   547600.0  
174   562500.0  
175   697225.0  
176   705600.0  
177   313600.0  

[178 rows x 19 columns]